#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const date = "20260830";
const plans = [
  ["Load", 10, 30, "SummaryReport"],
  ["Stress", 10, 60, "StatVisualizer"],
  ["Spike", 10, 10, "ViewResultsFullVisualizer"],
];
const sampler = (name, method, pathName, body = "", auth = false) => `
      <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="${name}" enabled="true">
        <stringProp name="HTTPSampler.domain">localhost</stringProp><stringProp name="HTTPSampler.port">3000</stringProp><stringProp name="HTTPSampler.protocol">http</stringProp><stringProp name="HTTPSampler.path">${pathName}</stringProp><stringProp name="HTTPSampler.method">${method}</stringProp><boolProp name="HTTPSampler.follow_redirects">true</boolProp><boolProp name="HTTPSampler.use_keepalive">true</boolProp><boolProp name="HTTPSampler.postBodyRaw">${body ? "true" : "false"}</boolProp>${body ? `<elementProp name="HTTPsampler.Arguments" elementType="Arguments"><collectionProp name="Arguments.arguments"><elementProp name="" elementType="HTTPArgument"><boolProp name="HTTPArgument.always_encode">false</boolProp><stringProp name="Argument.value">${body}</stringProp><stringProp name="Argument.metadata">=</stringProp></elementProp></collectionProp></elementProp>` : ""}
      </HTTPSamplerProxy>
      <hashTree><ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="${name} status assertion" enabled="true"><collectionProp name="Asserion.test_strings"><stringProp name="">200</stringProp></collectionProp><stringProp name="Assertion.test_field">Assertion.response_code</stringProp><intProp name="Assertion.test_type">2</intProp></ResponseAssertion></hashTree>`;
const make = (scenario, threads, duration, listener) => `<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.3"><hashTree>
  <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="23127185_${scenario}_${date}" enabled="true"><stringProp name="TestPlan.comments">Mai Thi Kim Duyen - member 2 - register/login/category/product/coupon/checkout</stringProp><boolProp name="TestPlan.functional_mode">false</boolProp><boolProp name="TestPlan.serialize_threadgroups">false</boolProp><elementProp name="TestPlan.user_defined_variables" elementType="Arguments"/></TestPlan><hashTree>
    <CSVDataSet guiclass="TestBeanGUI" testclass="CSVDataSet" testname="users.csv" enabled="true"><stringProp name="filename">${root}/jmeter/data/users.csv</stringProp><stringProp name="fileEncoding">UTF-8</stringProp><stringProp name="variableNames">name,email,password</stringProp><stringProp name="delimiter">,</stringProp><boolProp name="recycle">false</boolProp><boolProp name="stopThread">true</boolProp><boolProp name="shareMode">shareMode.all</boolProp></CSVDataSet><hashTree/>
    <CSVDataSet guiclass="TestBeanGUI" testclass="CSVDataSet" testname="products.csv" enabled="true"><stringProp name="filename">${root}/jmeter/data/products.csv</stringProp><stringProp name="fileEncoding">UTF-8</stringProp><stringProp name="variableNames">productId,searchTerm,quantity,totalAmount,couponCode,shippingAddress</stringProp><stringProp name="delimiter">,</stringProp><boolProp name="recycle">true</boolProp><boolProp name="stopThread">false</boolProp><boolProp name="shareMode">shareMode.all</boolProp></CSVDataSet><hashTree/>
    <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="${scenario} - ${threads} users" enabled="true"><stringProp name="ThreadGroup.on_sample_error">continue</stringProp><elementProp name="ThreadGroup.main_controller" elementType="LoopController"><boolProp name="LoopController.continue_forever">false</boolProp><intProp name="LoopController.loops">1</intProp></elementProp><stringProp name="ThreadGroup.num_threads">${threads}</stringProp><stringProp name="ThreadGroup.ramp_time">${Math.max(1, Math.floor(threads / 2))}</stringProp><longProp name="ThreadGroup.duration">${duration}</longProp><boolProp name="ThreadGroup.scheduler">true</boolProp></ThreadGroup><hashTree>
      <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="JSON and bearer headers" enabled="true"><collectionProp name="HeaderManager.headers"><elementProp name="Content-Type" elementType="Header"><stringProp name="Header.name">Content-Type</stringProp><stringProp name="Header.value">application/json</stringProp></elementProp><elementProp name="Authorization" elementType="Header"><stringProp name="Header.name">Authorization</stringProp><stringProp name="Header.value">Bearer \${token}</stringProp></elementProp></collectionProp></HeaderManager><hashTree/>
      ${sampler("Register", "POST", "/api/register", "{\"name\":\"\${name}\",\"email\":\"\${email}\",\"password\":\"\${password}\"}")}
      ${sampler("Login", "POST", "/api/login", "{\"email\":\"\${email}\",\"password\":\"\${password}\"}")}
      <JSONPostProcessor guiclass="JSONPostProcessorGui" testclass="JSONPostProcessor" testname="Extract token" enabled="true"><stringProp name="JSONPostProcessor.referenceNames">token</stringProp><stringProp name="JSONPostProcessor.jsonPathExprs">$.token</stringProp><stringProp name="JSONPostProcessor.match_numbers">1</stringProp></JSONPostProcessor><hashTree/>
      ${sampler("Categories", "GET", "/api/categories")}
      ${sampler("ProductList", "GET", "/api/products?search=\${searchTerm}")}
      ${sampler("ProductDetail", "GET", "/api/products/\${productId}")}
      ${sampler("AddToCart", "POST", "/api/cart", "{\"id\":\${productId},\"name\":\"iPhone 15 Pro Max\",\"price\":30000000,\"quantity\":\${quantity}}")}
      ${sampler("ApplyCoupon", "POST", "/api/apply-coupon", "{\"code\":\"\${couponCode}\",\"total_amount\":\${totalAmount},\"user_id\":2}")}
      ${sampler("Checkout", "POST", "/api/checkout", "{\"items\":[{\"id\":\${productId},\"name\":\"iPhone 15 Pro Max\",\"price\":30000000,\"quantity\":\${quantity}}],\"total_amount\":\${totalAmount},\"shipping_address\":\"\${shippingAddress}\"}")}
      ${sampler("Orders", "GET", "/api/orders/my-orders")}
    </hashTree>
    <ResultCollector guiclass="${listener}" testclass="ResultCollector" testname="${scenario} listener" enabled="true"><boolProp name="ResultCollector.error_logging">true</boolProp><objProp name="saveConfig"><value class="SampleSaveConfiguration"><boolProp name="time">true</boolProp><boolProp name="latency">true</boolProp><boolProp name="timestamp">true</boolProp><boolProp name="success">true</boolProp><boolProp name="label">true</boolProp><boolProp name="code">true</boolProp><boolProp name="message">true</boolProp><boolProp name="threadName">true</boolProp><boolProp name="dataType">true</boolProp><boolProp name="encoding">false</boolProp><boolProp name="assertions">true</boolProp><boolProp name="subresults">true</boolProp><boolProp name="responseData">false</boolProp><boolProp name="samplerData">false</boolProp><boolProp name="xml">false</boolProp><boolProp name="fieldNames">true</boolProp><boolProp name="responseHeaders">false</boolProp><boolProp name="requestHeaders">false</boolProp><boolProp name="responseDataOnError">true</boolProp><boolProp name="saveAssertionResultsFailureMessage">true</boolProp><boolProp name="bytes">true</boolProp><boolProp name="sentBytes">true</boolProp><boolProp name="url">true</boolProp><boolProp name="threadCounts">true</boolProp><boolProp name="idleTime">true</boolProp><boolProp name="connectTime">true</boolProp></value></objProp><stringProp name="filename">${root}/jmeter/results/${scenario.toLowerCase()}/23127185_${scenario}_${date}.jtl</stringProp></ResultCollector><hashTree/>
  </hashTree>
</hashTree></jmeterTestPlan>`;
for (const [s,t,d,l] of plans) { const dir=path.join(root,"jmeter","plans"); fs.mkdirSync(dir,{recursive:true}); let xml=make(s,t,d,l).replace(/<objProp name="saveConfig">[\s\S]*?<\/objProp>/, '').replaceAll('</CSVDataSet>', '<boolProp name="ignoreFirstLine">true</boolProp></CSVDataSet>').replaceAll('</ResponseAssertion></hashTree>', '</ResponseAssertion><hashTree/></hashTree>'); const extractor='<JSONPostProcessor guiclass="JSONPostProcessorGui" testclass="JSONPostProcessor" testname="Extract token" enabled="true"><stringProp name="JSONPostProcessor.referenceNames">token</stringProp><stringProp name="JSONPostProcessor.jsonPathExprs">$.token</stringProp><stringProp name="JSONPostProcessor.match_numbers">1</stringProp></JSONPostProcessor><hashTree/>'; xml=xml.replace('</ResponseAssertion><hashTree/></hashTree>\n      '+extractor, '</ResponseAssertion><hashTree/>'+extractor+'</hashTree>'); fs.writeFileSync(path.join(dir,`23127185_${s}_${date}.jmx`),xml); fs.mkdirSync(path.join(root,"jmeter","results",s.toLowerCase()),{recursive:true}); fs.mkdirSync(path.join(root,"jmeter","reports",s.toLowerCase()),{recursive:true}); }
